ID = 'id'
SUBMISSION_TIME = 'submission_time'
VIEW_NUMBER = 'view_number'
VOTE_NUMBER = 'vote_number'
TITLE = 'title'
MESSAGE = 'message'
IMAGE = 'image'
QUESTION_ID = 'question_id'
POST = 'POST'
GET = 'GET'
QUESTION = 'question'
IMG = 'img'
ANSWER = 'answer'
NONE = 'None'
UP = "UP"
DOWN = "DOWN"
QUOTATION_MARK = '"'
ANSWER_HEADER = "id,submission time,vote number,question id,message,image\n"
QUESTION_HEADER = "id,submission time,view number,vote number,title,message,image\n"
UTF_8 = 'utf-8'
WRITE = "w"
APPEND = "a"
READ = "r"
QUESTION_COMMENT = "question-comment"
